version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_orders
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    container_name: redis_cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"  # Порт для веб-интерфейса управления RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  fastapi_app:
    build: .
    container_name: fastapi_orders
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/fastapi_orders
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
  rabbitmq_data:
