"""Make password_hash not nullable

Revision ID: 612b5e63a598
Revises: 549a5010a5d0
Create Date: 2025-03-19 23:48:25.176043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612b5e63a598'
down_revision = '549a5010a5d0'
branch_labels = None
depends_on = None


def upgrade():
    # Обновляем email, делая его уникальным для каждой записи
    op.execute("""
        UPDATE users 
        SET email = CONCAT('temp_', uuid_generate_v4()::TEXT, '@example.com') 
        WHERE email IS NULL;
    """)

    # Обновляем password_hash, если он NULL
    op.execute("""
        UPDATE users 
        SET password_hash = 'temp_password' 
        WHERE password_hash IS NULL;
    """)

    # Делаем колонки обязательными
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(),
                    nullable=False)

    op.alter_column('users', 'password_hash',
                    existing_type=sa.VARCHAR(),
                    nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
