"""change items column type to JSON

Revision ID: 9894878d9370
Revises: b5731253b02f
Create Date: 2025-03-21 15:12:32.823399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9894878d9370'
down_revision = 'b5731253b02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
