"""Initial migration

Revision ID: 9ecf77261673
Revises: 9ec51d8fa442
Create Date: 2025-03-19 22:50:18.386849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecf77261673'
down_revision = '9ec51d8fa442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
