"""Добавлено created_at в orders (без NOT NULL)

Revision ID: acee30ab5595
Revises: 612b5e63a598
Create Date: 2025-03-20 21:11:08.055390

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'acee30ab5595'
down_revision = '612b5e63a598'
branch_labels = None
depends_on = None

orders_table = sa.table(
    "orders",
    sa.column("created_at", sa.DateTime())
)


def upgrade():

    op.add_column("orders", sa.Column("created_at", sa.DateTime(), nullable=True))

    op.execute(orders_table.update().values(created_at=datetime.utcnow()))

    op.alter_column("orders", "created_at", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
