"""Initial migration

Revision ID: b5731253b02f
Revises: acee30ab5595
Create Date: 2025-03-21 13:13:09.505566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5731253b02f'
down_revision = 'acee30ab5595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
